# Markets and Prices

@tomek2014[, Chapters 2--5]

## Choice and Individual Demand

A consumer at any given time faces an array of choices. These choices are linked with their *needs*. Ideally, the consumer would like to satisfy all of these needs, but their choices are constrained by their disposable income---the budget allocated for purchasing goods. The objective of a consumer, then, is to select a subset of goods that *best* satisfy their needs, subject to their budget constraint. 

Economists define "best" in terms of consumers' attempts to maximize their *utility*. Utility is an economic term describing satisfaction from the consumption of goods. While it is a unit-free measure, in general, more utility is better than less utility, and positive utility is "good" and negative utility is "bad."

Mathematically, for a set (or a basket) of goods, given by $\mathbf{x}=(x_1,\ldots,x_n)'$, the utility approach to the theory of demand is given by: $$\max U(\mathbf{x}),\;~~s.t.\;~\mathbf{p}'\mathbf{x} \leq M,$$ where $\mathbf{p}=(p_1,\ldots,p_n)'$ is a vector of prices for the given set of goods, and $M$ is the total disposable income (i.e., the budget). Thus, a consumer tries to attain the maximum utility they can afford, given their income and the prices of goods.

Market determines prices of goods---i.e., a consumer has no control over the prices. Changes to prices affect a consumer's decision--making. A consumer can afford and, typically, will pruchase more of the same good as the price of the good drops. This is known as the *substitution effect*. The substitution effect is always inversely related to the price change. 

Moreover, a decrease in price of a good, in effect, is equivalent to an increase in income---a consumer can afford more of all goods with the same amount of money. This is known as the *income effect*. The income effect, usually (but not necessarily), is inversely related to the price change. 

Thus, a price drop will typically increase the quantity demanded due to the income effect as well as the substitution effect. 

For some goods, real income and demand are inversely related. This is equivalent to the negative income effect due to price decrease. Such goods are called *inferior goods*. For inferior goods, the income and the substitution effects have opposite signs.

At the extreme, the income effect might outweigh the substitution effect, resulting in a positively sloped demand curve. This is known as *Giffen's paradox*, and such goods are referred to as the *Giffen goods*. It might occur, for example, when a staple commodity, such as rice, constitutes a large portion of consumer's expenditures. 

## Market Demand

We obtain aggregate or market demand when we add up (horizontally) individual consumer demand functions. Market demand is a schedule of product quantities that all consumers in a market are willing to purchase at given prices, everything else held constant. Normally, the demand curve is downward sloping, which is inferred in the *law of demand*.

Own price of the good is a sole factor affecting the quantity demanded, which results in *movement along the demand curve*. All other factors may influence demand by *shifting the demand curve*. These factors can be economic (e.g., prices and availability of other goods and services, income and its distribution); demographic (population size and its distribution by age, gender, ethnicity, etc.); tastes and preferences (influenced by information and advertising, lifestyle, etc.).

### Demand Elasticities

The responsiveness of quantity demanded to a price change---known as the own--price elasticity of demand (demand elasticity)---may vary from product to product, over time, and across locations. For example, quantity of salt purchased will not vary greatly due to the price change, but quantity of bananas purchased will likely be more responsive to price changes. From the consumers' standpoint: bananas have substitutes, but salt doesn't. As another example, quantity of rice purchased is likely to be less responsive to price changes in Asian countries, where it is considered a staple food, than in the Western world, where rice is viewed more as a side dish, perhaps with more substitutes.

Mathematically, price elasticity is given by: $$\epsilon = \frac{\partial Q}{Q}/\frac{\partial P}{P},$$ where $\partial$ denotes an infinitesimal change. Note that $\frac{\partial X}{X} \equiv \%\Delta X$, and so price elasticity is defined as the percentage change in quantity relative to the percentage change in price. That the elasticity is measured in relative (or percentage) terms, makes it an attractive measure as it facilitates a direct comparison between goods with possibly different units of measurement of quantities and prices. 

The foregoing equation can be rewritten as: $$\epsilon = \frac{\partial Q}{\partial P}\frac{P}{Q},$$ where $\frac{\partial Q}{\partial P}$ is the slope of the demand curve. Because of the downward-sloping demand curve, the price elasticity measure ranges from zero to negative infinity. This range consists of *inelastic* ($|\epsilon_{ii}| < 1$) and *elastic* ($|\epsilon_{ii}| > 1$) segments, with $|\epsilon_{ii}| = 1$ representing the *unitary elastic* case.

For most functional forms, including the linear demand, the elasticity coefficient varies along the demand curve. Exceptions are if demand is represented by a straight horizontal line, a straight vertical line, a power function, and a rectangular hyperbola. In general, however, demand for different goods are usually categorized as elastic or inelastic.

The responsiveness of the demand for a good $i$ to a price changes of a related good $j$ is known as the cross--price elasticity of demand (cross--price elasticity). Mathematically, cross-price elasticity is given by: $$\epsilon_{ij} = \frac{\partial Q_i}{Q_i}/\frac{\partial P_j}{P_j},$$ or, alternatively: $$\epsilon_{ij} = \frac{\partial Q_i}{\partial P_j}\frac{P_j}{Q_i}$$

Three types of relationships---which are related to the substitution effect---can be identified depending on the sign of cross-price elasticity: for substitute goods, $\epsilon_{ij} > 0$; for complement goods, $\epsilon_{ij} < 0$; and for independent goods, $\epsilon_{ij} = 0$

Note that the price change also facilitates the income effect. If the income effect outweighs the substitution effect, we might observe a negative relationship between the demand for product $i$ and the change in price of product $j$, even when the two are substitutes. To the extent that the expenditure share of a given good is a small fraction of the disposable income, the substitution effect will typically dominate the income effect.

The responsiveness of the demand for a good to income changes is income elasticity of demand (income elasticity). Mathematically, income elasticity is given by: $$\epsilon_{m} = \frac{\partial Q}{Q}/\frac{\partial M}{M},$$ or, alternatively: $$\epsilon_{m} = \frac{\partial Q}{\partial M}\frac{M}{Q}$$

In most cases, the income elasticity of demand has a positive value: as income increases, consumers tend to buy more of most products. However, income elasticities tend to decline as incomes increase. In general, demand is thought to be a nonlinear function of income. In practice, expenditures (rather than income) are often used to estimate "income" elasticities.


## Supply by a Single Firm

Much like consumers are utility--maximizers, the firms are profit--maximizers. For a firm producing a product, $q$, using a set of inputs, $z=(z_1,\ldots,z_k)'$ , the short-run profit is defined as: $$\pi = pq-w'z,$$ where $p$ is a unit price of $q$, and $w=(w_1,\ldots,w_k)$ is a vector imput costs.

A firm's output is related to the inputs through a production function: $$q = q(z)$$

The profit function, thus, can be rewritten as: $$\pi = pq(z)-w'z.$$ This equation can be used in deriving the producer's supply function of output and demand functions for inputs. 
<!-- The relevant supply function depends on the form of the production function, hence the form of the cost functions. -->

A producer maximizes profits by using each factor up to the point where the last unit just pays for itself. Optimal use of input is determined with respect to the (known) production function. The functional form of production is such that output is increasing with input, but at a decreasing rate. The rate of increase in output is called the *marginal (physical) product* of input: $$MP_i=\frac{\partial q}{\partial z_i}$$

Following the rule of profit maximization, the optimum level of factor use is at the point where the $MP_i$ multiplied by price of output, $p$, just equals to the unit cost of input, $w_i$, which yields the following relationship:$$\frac{\partial q}{\partial z_i} = \frac{w_i}{p}$$

This relationship implies that an increase of the input cost, will lead to reduced use of that input and lower output, everything else held constant. Moreover, optimal factor use will change only with an increase or decrease in relative prices.

## Market Supply

Market supply is a (horizontal) aggregate of individual firm's supply curves. Assuming $n$ identical firms, each producing $q$ units of optimal output, the aggregate market supply is $Q = nq$. The supply curve, generally, is upward sloping, which is inferred in the *law of supply*. 

Own price of a good is a sole factor affecting the quantity supplied resulting in the movement along the supply curve. All other factors affect supply by *shifting the supply curve*. Such factors can be: prices of inputs; prices of related goods; goods competing for the same factors of production (e.g., the same land for corn and soybeans); joint production of goods (e.g., soybean meal and soybean oil); factors affecting production costs and output quantities (e.g., technology and weather); production risks; taxes and subsidies, etc.

### Supply Elasticity

The responsiveness of the supply to price changes is known as *price elasticity of supply* (supply elasticity). Mathematically, supply elasticity is given by: $$\eta = \frac{\partial Q}{Q}/\frac{\partial P}{P} \equiv \frac{\partial Q}{\partial P}\frac{P}{Q}$$

In the very short run, supply is perfectly inelastic (vertical line) and the elasticity is zero. Inelastic supply refers to elasticity measures between $0$ and $1$. Elastic supply refers to elasticity measures greater than $1$. A perfectly elastic supply (horizontal line) has the elasticity measure or $\infty$.

Assuming a linear supply curve, as quantity and price increase (i.e., as we move upwards along the supply curve) the price elasticity of supply converges to $1$. Moreover, if a linear supply curve intersects with the origin, the elasticity of supply is always $1$.


## Structure and Price Determination

To begin, we assume that there are many sellers and buyers in a market, and that each individual seller or buyer cannot influence the market. Furthermore, we assume that the product is homogenous, that there are no costs associated with enetring and leaving the market, and that the information on economic forces that are determining prices is complete and freely available for market participants. Such market is referred to as a perfectly competitive market. 



 

<!-- \begin{frame}{Consumer Demand} -->

<!-- 	\begin{center} -->
<!-- 		\begin{tikzpicture}[x=0.8cm,y=0.45cm] -->
<!-- 		% choose precision -->
<!-- 		\def\samp{100} -->

<!-- 		% define parameters -->
<!-- 		\def\cc{10} % U(0) -->
<!-- 		\def\dd{5} % a -->
<!-- 		\def\ee{10} % b -->

<!-- 		% define utility functions -->
<!-- 		\def\A{\x,{\cc+sqrt{\dd*\dd-(\x-\ee)*(\x-\ee)}}} -->

<!-- 		% Draw and label curves -->
<!-- 		\draw[solid,domain=0:10,color=blue] (1,9) arc (-170:-100:4.0cm) node[right] {$U_A$}; -->
<!-- 		\draw[solid,domain=0:10,color=blue] (2,10) arc (-170:-100:3.5cm) node[right] {$U_B$}; -->
<!-- %		\draw[solid,domain=0:10,color=blue] (3,11) arc (-170:-100:3.0cm) node[right] {$U_C$}; -->

<!-- 		\uncover<2->{ -->
<!-- 			\draw[solid,domain=0:10,color=red] (0,9.9) -- (4.0,0); -->
<!-- 			\draw[solid,domain=0:10,color=red] (0,9.9) -- (7.6,0); -->
<!-- 		} -->

<!-- 		\uncover<3->{ -->
<!-- 			\draw[dotted,domain=0:10,color=green] (0,5.5) -- (1.8,5.5) node[above right] {$A$}; -->
<!-- 			\draw[dotted,domain=0:10,color=green] (1.8,5.5) -- (1.8,0); -->

<!-- 			\draw[dotted,domain=0:10,color=green] (0,5.0) -- (3.8,5.0) node[above right] {$B$};; -->
<!-- 			\draw[dotted,domain=0:10,color=green] (3.8,5.0) -- (3.8,0); -->
<!-- 		} -->

<!-- 		% Add axes -->
<!-- 		\draw[arrow] (0,0) -- (12,0) node[below=0.1cm] {$x_1$}; -->
<!-- 		\draw[arrow] (0,0) -- (0,12) node[left=0.1cm] {$x_2$}; -->

<!-- 		\end{tikzpicture} -->
<!-- 	\end{center} -->

<!-- \end{frame} -->




<!-- \begin{frame}{Individual Demand} -->

<!-- 	\begin{center} -->
<!-- 		\begin{tikzpicture}[x=0.8cm,y=0.45cm] -->
<!-- 		% choose precision -->
<!-- 		\def\samp{100} -->

<!-- 		% define parameters -->
<!-- 		\def\cc{10} % U(0) -->
<!-- 		\def\dd{5} % a -->
<!-- 		\def\ee{10} % b -->

<!-- 		% define utility functions -->
<!-- 		\def\A{\x,{\cc+sqrt{\dd*\dd-(\x-\ee)*(\x-\ee)}}} -->

<!-- 		% Draw and label curves -->
<!-- 		\draw[solid,domain=0:10,color=blue] (1,9) arc (-170:-100:4.0cm) node[right] {$U_A$}; -->
<!-- 		\draw[solid,domain=0:10,color=blue] (2,10) arc (-170:-100:3.5cm) node[right] {$U_B$}; -->
<!-- %		\draw[solid,domain=0:10,color=blue] (3,11) arc (-170:-100:3.0cm) node[right] {$U_C$}; -->


<!-- 		\draw[solid,domain=0:10,color=red] (0,9.9) -- (4.0,0); -->
<!-- 		\draw[solid,domain=0:10,color=red] (0,9.9) -- (7.6,0); -->
<!-- 		\draw[very thick,dashed,domain=0:10,color=red] (0,7.2) -- (5.5,0); -->

<!-- 		\draw[dotted,domain=0:10,color=green] (0,5.5) -- (1.8,5.5) node[above right] {$A$}; -->
<!-- 		\draw[dotted,domain=0:10,color=green] (1.8,5.5) -- (1.8,0); -->

<!-- 		\draw[dotted,domain=0:10,color=green] (0,5.0) -- (3.8,5.0) node[above right] {$B$};; -->
<!-- 		\draw[dotted,domain=0:10,color=green] (3.8,5.0) -- (3.8,0); -->

<!-- 		\draw[dotted,domain=0:10,color=green] (0,3.5) -- (2.8,3.5) node[above right] {$C$};; -->
<!-- 		\draw[dotted,domain=0:10,color=green] (2.8,3.5) -- (2.8,0); -->


<!-- 		% Add axes -->
<!-- 		\draw[arrow] (0,0) -- (12,0) node[below=0.1cm] {$X_1$}; -->
<!-- 		\draw[arrow] (0,0) -- (0,12) node[left=0.1cm] {$X_2$}; -->

<!-- 		\end{tikzpicture} -->
<!-- 	\end{center} -->

<!-- \end{frame} -->



<!-- Fixed Cost (FC) -->
<!-- Average Fixed Cost (AFC) = $\frac{FC}{q}$ -->
<!-- Variable Cost (VC) -->
<!-- Average Variable Cost (AVC) = $\frac{VC}{q}$ -->
<!-- Total Cost (TC) = FC + VC -->
<!-- Average Total Cost (ATC) = $\frac{TC}{q}$ -->
<!-- Marginal Cost (MC) = $\frac{\partial TC}{\partial q} = \frac{\Delta TC}{\Delta q}$ -->


<!-- \begin{frame}{The Firm} -->

<!-- \begin{center} -->
<!-- \begin{tikzpicture}[scale=.36] -->
<!-- % choose precision and scale of plot -->
<!-- \def\samp{100} -->

<!-- % define parameters -->
<!-- \def\aa{20} % fixed costs -->
<!-- \def\bb{1} % variable costs -->
<!-- \def\cc{5} % (constant) marginal costs -->


<!-- % define monopoly profit function -->
<!-- \def\mc{{\x},{6-1.3*\x+.09*\x^2}} % marginal cost -->
<!-- \def\atc{{\x},{(\aa+6*\x-0.65*\x^2+.03*\x^3)/\x}} % average total cost -->
<!-- \def\avc{{\x},{(6*\x-0.65*\x^2+.03*\x^3)/\x}} % average variable cost -->
<!-- \def\afc{{\x},{(\aa)/\x}} % average fixed cost -->

<!-- % Draw and label monopoly profits -->
<!-- \draw[curve,domain=2:20,color=red] plot[samples=\samp] (\mc) node[right] {$MC$}; -->
<!-- \draw[curve,domain=2:20,color=blue] plot[samples=\samp] (\atc) node[right] {$ATC$}; -->
<!-- \draw[curve,domain=2:20,color=green] plot[samples=\samp] (\avc) node[right] {$AVC$}; -->
<!-- \draw[curve,domain=2:20,color=gray] plot[samples=\samp] (\afc) node[right] {$AFC$}; -->

<!-- % Add axes -->
<!-- \draw[arrow] (0,0) -- (26,0) node[below=0.05cm] {$q$}; -->
<!-- \draw[arrow] (0,0) -- (0,16) node[left=0.05cm] {$C(q)$}; -->

<!-- \end{tikzpicture} -->
<!-- \end{center} -->

<!-- \end{frame} -->
