# Marketing System and Margins

When we enjoy our pizza at a restaurant, or an oven roasted chicken at home, rarely (if at all) we contemplate about the chain if events---a system, and the actions of people involved in this system---that has brought the meal to our table. This *agricultural marketing system*, also known as the *food system*, links producers with consumers by transforming an agricultural commodity into a food product. 
<!-- The activities that facilitate this transformation can be tangible (e.g., storage, transportation, processing) or intangible (e.g., grading, risk-bearing, financing); but they all add value to agricultural commodities at different stages of the *supply chain*.  -->

<!-- ```{r, echo = FALSE, message=FALSE, eval = TRUE} -->
<!-- library(DiagrammeR) -->
<!-- grViz("digraph { -->

<!--       # graph [layout = dot, rankdir = LR] -->

<!--       node [fixedsize=true,fontname=Helvetica,fontsize=24,shape=egg,penwidth=3,width=2.4,height=1.2,color=slategray3,fontcolor=slategray3] -->

<!--       edge[color=slategray3,arrowhead=vee] -->

<!--       A [label='Producer'] -->
<!--       B [label='Processor'] -->
<!--       C [label='Retailer'] -->
<!--       D [label='Consumer'] -->

<!--       A -> B -> C -> D -->

<!--       }") -->
<!-- ``` -->

 <!-- When this is done optimally, markets are said to be 'efficient.' Market efficiency is intrinsically linked with demand and supply, the interaction of the two, and the manner in which this interaction is manfested into prices. -->

## Vertical Coordination

Although farmers and consumers sometimes directly interact (e.g., farmers markets), most food products usually go through a complex processing and distribution system after they leave the farm-gate and before they land on a shelf of a retail store. In the process, the usually bulky, perishable, and homogeneous farm commodities are transformed into more concentrated, storable, and differentiated food products. 

The agricultural marketing system consists of multiple stages, and involves a number of intermediaries, such as processors, distributors, wholesalers, and retailers. Between each stage of the system there is a market. Within each market a price is determined. Prices aggregate a great deal of information, and play an integral role in conveying this information between food consumers and commodity producers.

The longer and more complex is the marketing system, the more difficult it becomes to relay information from a consumer to a farmer. A profit-maximizing farmer will only supply a better quality commodity, or add a certain attribute to the commodity, if they are rewarded for it. When the reward exceeds costs, the farmer will take actions to supply a commodity with desired qualities. In presence of uncertainty surrounding the rewards (prices), as well as information asymmetry among buyers and sellers within the marketing system, ensuring that the desired product attributes are present for the right price may be a challenging (if not an impossible) task.

One way to facilitate coordinated perdormance among members of the supply chain is by means of contracting. A contract is an arrangement between a buyer and a seller, where the parties agree on quantity and price of a commodity to be exchanged months in advance. There are different degrees of 'involvement' in contractual agreements; in more 'involved' instances, a processor supplies all the inputs, and assumes market risks, while a farmer supplies farm facilities and is responsible for agreed-upon commodity production. 

At the extreme, two or more segments of a supply chain go under the same ownership, which is referred to as *vertical integration*. Downstream integration is when a firm begins producing inputs that they previously purchased from their supplier. Upstream integration is when a firm begins performing a function of a firm that previously purchased their product.  

<!-- Multiple benefits are associated with vertical integration: (i) it lowers transaction costs; (ii) it reallocates some of the market risk; (iii) it increases efficiency in resource allocation, production, and distribution.  -->


<!-- %\begin{frame}{Agricultural Marketing} -->
<!-- % -->
<!-- %\begin{itemize} -->
<!-- %	\item The role of retailers is crucial in the marketing system. -->
<!-- %	\item Because of their size, market power, and strategic position, food retailers are making many of the major market decisions about quantity, quality, and services provided by the entire food industry. -->
<!-- %	\item Their marketing decisions are directed toward satisfying consumer wants and needs, as well as influencing their preferences. -->
<!-- %\end{itemize} -->
<!-- % -->
<!-- %\end{frame} -->


## Marketing Margins

In the farm-retail price relationship, the difference between what consumers pay and what farmers receive is called *price spread*, also known as *marketing margin*. Consider a profit maximizing retailer, which uses a farm commodity and marketing services as inputs in production. The profit function of this retailer can be given by: $\pi = p^r q^r - p^f q^f - C^r(q^r)$ where $p^r$ and $p^f$ are retail and farm prices; $q^r$ and $q^f$ are product output and commodity input quantities; and the last term, $C^r(q^r)$, represents the retailer's marketing cost function. 

For simplicity, let $q^r=q^f=q$, which reduces the profit function to: $\pi = (p^r - p^f) q - C^r(q)$, where $p^r - p^f$ is the price spread.

Marketing costs, $C^r(q)$ can be modeled as a linear function of quantity produced: $$C^r(q) = c^r q,$$ where $c^r > 0$ is a constant. In such case, marginal marketing cost is the same for any $q$: $$\frac{\partial C^r(q)}{\partial q} = c^r\;~~\forall\;q.$$ This model is consistent with a simple markup rule: the retail price is equal to the wholesale price plus a constant (which is based on the cost of the marketing inputs).

Alternatively, and perhaps more realistically, marketing costs can be modeled, as nonlinear function of quantity produced. The usual assumption, in that case, would be that the first derivative of the marketing costs function should be positive, while the second derivative can be positive or negative (i.e., marketing costs should be increasing with output, but they may be increasing at an increasing rate or a decreasing rate). 

Because of a complex marketing system, variables other than just prices and quantities of inputs and outputs may be important in determining the margins. Some of such fuctors include changes in cost of the marketing services that get the farm product to the consumer in the form they demand (e.g., improvements in technology in the marketing system); changes in factor composition, over time, that may increase the total cost of marketing services (e.g., additional marketing services can emerge, that were not available or feasible before); changes in government programs (e.g., taxes and subsidies); changes in  market power of firms in the marketing system, resulting in: increased prices paid by a consumer, or reduced prices received by a farmer (or both).


## Derived Demand, Elasticity, and Market Power

Assuming linear demand functions, and constant marketing costs, elasticity of derived demand (faced by a farmer) can be given by: $\epsilon^f = \epsilon^r\frac{p^f}{p^r}$ where $\epsilon^r$ is elasticity of primary demand (in a retail market), and $p^f$ and $p^r$ are the farm commodity and the retail product prices. It follows that the farm-level demand is more price inelastic than the retail demand. The larger is the marketing margin the larger is the difference between the two elasticities to the point that even though the retail demand is price elastic, the derived demand may end up being price inelastic.




<!-- These intermediaries manifest the division of labor and facilitate specialization; as such, their actions usually are marked by *economies of scale*.  -->

<!-- The intermediaries also help mitigate the search and transaction costs.  -->

<!-- To the extent that this is a valude-adding transformation, the farm-value share of a product decreases. This decrease varies across commodities, and depends on value added during the processing and distribution stages.  -->

