# International Agricultural Trade

Countries trade because some can produce certain commodities when others cannot (absolute advantage), or, more typically, because some can produce certain commodities more efficiently than others (comparative advantage). 

*Spatial equilibrium models* can help determine the optimum trading patterns, given the supply and demand conditions within each country (market). We illustrate this using two competitive markets. 

In absence of transfer costs, the intersection of the excess demand and excess supply curves yields the world price. A more realistic scenario is trade with transfer costs. A way to think of the effect of transfer costs is by incorporating them into the supply function of the exporting country.

Transfer costs increase the price at which commodities are traded, and reduce the quantity of traded commodities. As a result, in an importing market, consumers receive less of the commodity for a higher price, and producers sell more of the commodity for a higher price; the opposite is true in an exporting market.


## Gains from Trade

Gains from trade can be grouped into two categories: gains from exchange, and gains from specialization.

Drawing supplies from a world market allows access to a wider array of products at lower cost and perhaps with greater security of supply than can be produced by domestic industries. Lower prices from imported goods allow consumers to buy more goods from disposable income. Lower prices for imported raw materials, that are used to produce final goods, also benefit consumers by lowering prices of these final goods. All these facilitate greater savings, which lead to increased investment and greater economic growth.

Trade stimulates the expansion of low cost industries (and forces the contraction of high cost industries). Increase of the size of the market allows firms or industry to take advantage of economies of scale. Increase of competition provides greater emphasis on technological development and innovation, and results in increased skills of workforce.

	
## Trade Liberalization vs Protectionism	
	
The case for free trade is that producers and consumers allocate resources most efficiently when governments do not distort market prices through trade policy. Economic welfare of a small country is highest with free trade. With restricted trade: consumers pay higher prices (than they would have paid otherwise); distorted prices cause overproduction either by existing firms producing more or by more firms entering the market. 

Protectionism consists of set of actions that deviates the trade patterns from what would have been their state in absence of any regulations (i.e., in a free trade regime). The case for protectionism is primarily directed to maintain a considerable degree of self--sufficiency in the country, but can also be 're-active' to ongoing economic or political processes. Common levers for trade restriction are tariffs and quotas. Other government interventions that can play the role of trade distortions are taxes and subsidies.

In agriculture, strongly divergent climatic conditions around the globe, create ideal conditions for making use of comparative advantage. And while it would seem that free trade should be particularly attractive and relevant in agriculture, it has been traditionally an area where governments have been reluctant to open up domestic markets to international trade. Typical pattern is that developed countries tend to maintain high domestic prices, to protect farmers' incomes, while developing countries tend to keep domestic prices low, in the interest of consumers.


<!-- ## Terms of Trade -->

<!-- Terms of trade denotes export prices in terms of import prices. A large country can alter terms of trade in their favor by means of trade restrictions (e.g., tariffs or quotas) or equivalent trade distortion mechanisms (e.g., taxes). The welfare effect of this is nonlinear, however. That is, a small tariff may lead to an increase in national welfare, but at some tariff rate, the welfare will begin to decrease as the economic efficiency loss exceeds the terms of trade gain. Likewise, an export tax that completely prohibits exports leaves a country worse off; but an export tax rate may exist that maximizes national welfare through the terms of trade. The foregoing ignore likelihood that other countries may retaliate against the large country by enacting their own trade restrictions. -->


## Trade Negotiations and GATT

After the World War II, nations around the world recognized the urgent need for coordinated policy efforts in the areas of economic development, monetary policy, and international trade. With that in mind---and after the United States Congress refused to sign on an agreement reached by the Bretton Woods participants to form the International Trade Organization---23 nations signed a multilateral agreement regulating international trade known as the General Agreement on Tariffs and Trade (GATT) in Geneva on 30 October 1947 to take effect on 1 January 1948. GATT became the vehicle for trade negotiations for the next half century, until its successor---the World Trade Organization (WTO) was formed and took effect in 1995.

Main principles of the GATT involved: 

- *most--favoured--nation* principle, meaning that trade benefits conferred on one country should be extended unconditionally to all other member countries; 
- *national treatment*, meaning that imports should be treated no less favourably than domestic products; and 
- *reciprocity*, meaning that negotiations should be conducted on a reciprocal and mutually advantageous basis.

### Agriculture in Trade Negotiations

Idea of replacing agricultural price support with direct payments to farmers decoupled from production dates back to the late 1950s. Twelfth session of the GATT Contracting Parties selected a Panel of Experts, chaired by Gottfried Haberler, to examine the effect of agricultural protectionism, fluctuating commodity prices, and the failure of export earnings to keep pace with import demand in developing countries. The report (1958) found that there was a decline in the terms of trade for primary commodities (relative to the manufactured goods). This finding accords with what later became to be known as the *Prebisch--Singer hypothesis* (though Haberler himself had particular disagreement was with the idea that there was a systematic long-term decline in the terms of trade). The report stressed the importance of minimizing the effect of agriculture subsidies on competitiveness; recommended replacing price support with direct supplementary payments not linked with production; anticipated discussion on green box subsidies---the kind of subsidies that do not distort trade, or at most cause minimal distortion; that are government-funded (not by charging consumers higher prices); and that do not involve price support.

In 1980s, global economy had entered a cycle of recession, which led to a collapse of agricultural commodity prices. Financial and economic costs of agricultural policies rose sharply in many industrialized countries. Perception that opening up markets could improve economic conditions, and generate much needed efficiency gains, facilitated a new round of multilateral trade negotiations. 

In leading up to the 1986 negotiations, developed countries strongly resisted compromises on agriculture. This opposition was subsequently neutralized by guaranteeing farmers continued support, and allowing subsidies that cause not more than minimal trade distortion in order to meet public policy aims. 

### Uruguay Round

Agreement on Agriculture, which was reached in the third and final phase of the Uruguay Round, continues to be the most substantial trade liberalization agreement in agricultural products in the history of trade negotiations. The agreement revolved around the following three directions:  

- Market access: convert of all existing non-tariffs into tariff equivalents (and, where necessary, guarantee minimum access to domestic markets through the creation of tariff-rate quotas); developed countries to reduce tariffs by 36\% over six years, with a minimum rate of reduction of 15\% for each tariff lines; developing countries to cut tariffs by an average of 24\% over 10 years; safeguard provisions to allow importers to guard against import surges and low world prices.
- Export competition: export subsidies were capped and then reduced in both value (36\%) and volume (21\%). In Nairobi in 2015, WTO members agreed that developed countries would immediately remove export subsidies except for a handful of agriculture products and that developing countries would do so by 2018.
- Domestic support: reduction of the level of sector--wide (rather than product--specific) support---better known as the aggregate measurement of support---by 20\% over six years for developed countries, and 13\% over 10 years for developing countries.


