# Dynamic Price Relationships

Over time, demand and supply are influenced by changes to their underlying factors. The dynamic behaviour of prices is a consequence of such changes. This may result in trends, cycles, and seasonality in the commodity prices dynamics. A commodity price series may exhibit one or several of these features (e.g., seasonality is a likely feature of annually harvested agricultural commodity prices; prices of meat typically resemble cyclical patterns, etc.). Over time, the underlying factors of a commodity price behaviour may change. For example, previously perishable products---such as meat, eggs, butter---became "storable" with invention of refrigeration, which had an important impact on price dynamics of a range of affected commodities [e.g., @goodwin2002].


## Trends and Shifts in Price Levels

Commodity prices may exhibit shifts in average price levels. A continuum of such shifts result in price trends. Trends usually are manifested by persistent upward (or downward) movements in prices over a reasonably long period of time. Recall that observed prices are equilibrium market prices, governed by supply and demand schedules. For an observable trend in a commodity price series, continuous relative shifts in supply and demand must occur. For example, a continuous stream of new production technology may cause the supply function to steadily shift rightward, resulting in a downward trend in observed prices. 

For agricultural commodities, a major factor in year-to-year price variability is change in annual supply. Crops have swings in annual production, because changing expectations about returns as well as climatic and biological factors of production. Inventories and imports may mitigate the effects of a small crop in a particular region, unless the effect has worldwide manifestation. 

In contrast to year-to-year changes, there are occasions when price levels shift to (and remain at) a new level. This may happen as a result of an abrupt (or, possibly, gradual within a relatively short period of time) structural change in commodity markets. For example, the entry of the former Soviet Union into the world market for grains in 1973 created a new source of demand that persisted, which resulted in a substantially high nominal prices. More recently, the so-called "ethanol boom" in the U.S. has shifted the prices of corn to a new, higher level. Although it is difficult to ascertain whether a change in a price level is transitory of persistent, shifts in price levels should be distinguished from continuous trends.


## Price Cycles and the Cobweb Model

A cycle is a pattern that repeats itself over a time period that is longer than one year. The simplest variant of a price cycle has a fixed period (length of time, say, from peak to peak), but it rarely is the case. Cycle-like behaviour of prices is typically initiated by an external event (say, a drought). Such events may manifest themselves irregularly, and thus price cycles may also be characterized with irregular cycles. Moreover, due to the very nature of production process, the cycles may be asymmetric -- a positive shock of a given magnitude may result in subsequent dynamic behaviour, which may be different from dynamics due to a negative shock of the same magnitude.

Two factors facilitate cyclical behaviour in commodity prices: (i) the way expectations are formed, and (ii) the costs associated with responding to changed expectations. Due to the production lag, profit-maximizing decisions rely on expected (rather than actual) prices.

To illustrate the point, consider a case of *naive expectations*: $$p_{t+1}^{*} = p_{t}$$ where $p_{t+1}^{*}$ denotes the expected price for period $t+1$, which is equal to an observed price in period $t$. In addition, assume a competitive market (producers are price-takers), a market clearing price adjustment, and static supply and demand. Under the foregoing assumptions, 

Somewhat more "sophisticated" models assume some form of *adaptive expectations*. Such models incorporate multiple lags of prices (i.e., $p_{t-1},p_{t-2},\dots$) in forming the expected price of a commodity. The expected price then can be a geometric-weighted average of current and past prices, or a prediction from an autoregressive process. To that end, the naive expectations is a special case of the adaptive expectations.


## Seasonality of Agricultural Commodity Prices

Seasonal price behaviour is a systematic pattern that occurs within a year, and repeats across the years. For food and agricultural commodities, the main source of seasonality is the supply-side effects. Although, demand-side effects are also occasionally evident (e.g., high demand for turkey meat in the U.S. around the Thanksgiving period in November). Assuming an annually produced storable commodity, and a perfectly competitive market, prices will be lowest just after the harvest, and rise at the rate of *cost of storage* per unit of time.

The typical seasonal price pattern does not prevail each year. Prices may rise by more than the cost of storage, or they may even decline over the season. Economic agents act upon information related to expected production, available stocks, and expected changes in demand for a commodity. But the information is subject to change throughout the season. And prices will reflect those changes.

The storage costs within a year, implicitly depicted in the seasonal pattern, can be divided into four components: The costs of inputs; The opportunity costs (which depends on the price of the commodity and interest rates); The convenience yield (of holding stocks); The risk associated with the expected future price of a commodity

Not only prices increase, but they also become more variable as the storage season progresses. i.e., the price variability immediately after harvest is smaller than the price variability during months later in the marketing year. Within a marketing year, inventories are declining, and when inventories are small late in the season, changes in expectations can have a large price effects (spikes).


## Economics of Storage

Storage has important price--stabilizing role over the marketing year, as it creates a pricing buffer by shifting stocks forward. When aggregated across the whole market, the storage adjustments by individual traders reduce price fluctuation over time.

In general, the driving force in price behaviour is *intertemporal arbitrage* by economic agents. Mathematically, intertemporal arbitrage is given by the following equilibrium condition: $$E\left(p_{t+1}|\Omega_t\right)-p_{t} = s_t,$$ where $s_t$ is the marginal cost of storage between periods $t$ and $t+1$. That is, for any fixed period of storage, difference between the expected future price and the current price of a commodity must exactly equal the marginal cost of storage for that time interval.

The aforementioned is referred to as the law of one price in a temporal context. If, for example, the expected price exceeds the current price by more than the cost of storage, an incentive would exist to store a larger amount for future use. This, in turn, will have the effect of raising the current price and reducing the expected price. The process will continue until the equilibrium condition is met.

