# Risk and Uncertainty

Because of complexities of physical and economic systems in agriculture, most processes that economic agents care about unfold with some degree of uncertainty. Uncertainty means that any given action can lead to many possible outcomes, albeit some more likely than others. Thus, decision--making under uncertainty is characterized by risk, as not all possible consequences are equally desirable.

Uncertainty in agricultural markets (or any markets, for that matter) is an issue because a typical person is risk--averse. A person is said to be risk--averse if, for every lottery $F(w)$, where $w$ is realized wealth, they will always prefer (at least weakly) the certain amount $E(w)$ to the lottery itself. That is, $$U\left[\int w dF(w)\right] \ge \int U(w)dF(w).$$

A discrete variant of the foregoing can help with an illustration. A risk--averse person would prefer a guaranteed pay-out of \$100 rather than a pay-out of either \$0 or \$200 each with probability of 50\%.  

Under the assumption of monotonically increasing concave utility function, $U(w)$, we can derive the notions of absolute risk aversion, $$A(w) = -U''(w)/U'(w),$$ and of relative risk aversion, $$R(w) = wA(w).$$ To the extent that agents will become less averse to a gamble as their wealth grows, $A(w)$ can be seen as a decreasing function of $w$; there are no *a priori* expectations regarding any particular behavior of $R(w)$ with respect to $w$.

The key sources of uncertainty and risk that face an agricultural producer are related to: 

- Production---agricultural producton heavily relies on exogenous factors, such as weather, which can be important source of idiosynchratic uncertainty. 
- Price---production decisions are made far in advance of realizing the output and prices. 
- Technology---technological advancement may make quasi--fixed investments obsolete. 
- Policy---government, through its policies, plays an important role in agriculture, and any changes to these policies creates considerable risk for agricultural investments.

## Managing Risk via Futures Markets

One mechanism to mitigate risk in agriculture is via hedging, which shifts the price risk. The acquisition of a futures contract can help manage risk by assuring (approximately) a given level of returns. From the standpoint of an *arbitrage hedge*, if the expected convergence of the spot and futures prices at some future time period is sufficient to cover storage costs, an agent can assure the return by hedging.

Another way to look at hedging on futures markets, is its ability assist a firm in assuring a return from their business activities. A merchant can make a bid on a contract to export certain amount of commodity, without actually having (enough of) it in possession; or, they can offer farmers forward contracts at planting time to purchase their grain at the harvest. This is referred to as an *operational hedge*, which can be seen as a temporary substitute for later transactions in the cash market.

Futures markets can assist a producer to price their output before it is produced. Similarly, a processor can also price the input, prior to the actual purchase of the physical commodity. Thus, an *anticipatory hedge* is based on expected future actions, such as the production and sale of the commodity. An anticipatory hedge can lock in a profit, when price relationships are favourable.

Assuring the return by hedging, crucially relies on the assumption of convergence. Convergence may not be exact (most of the time it is not). As a consequence, hedges do not give perfect results, which is also known as *basis risk*. Thus, basis risk, or our inability to forecast convergence with certainty, poses a problem for hedgers. Another related risk is inherent to the production risk: in times of a negative supply shock, a portion of the hedge, in effect, will turn into a speculative position, which can result in a loss on the position in futures.


## Managing Risk via Insurance

An alternative mechanism to mitigate risk in agriculture, which by no means is a substitute to producers' participation in futures markets, is via crop insurance. A substantial production (and price) variability, has led producers realize the importance of risk management as a component of their expected profit-maximization strategies. A producer can take control of risk management, or outsource it. a firm may build up its own funds to cover sudden losses; or a firm can transfer this risk to an insurer for a fee.

Insurance companies are specialized risk bearers that spread the risk over a wide area and groups of people or businesses. Sometimes, government price-- and revenue--supporting programs can serve as a mechanism to mitigate the risk (but availability of such programs vary from country to country). In fact, while crop insurance markets have existed for a long time in some parts of the world, their existence has depended crucially on government support.

Private agricultural insurance markets may fail because the costs of maintaining these markets imply unacceptably low average payouts relative to premiums. Moreover, the perceived demand for crop insurance may be overstated because farmers have an option to manage the risk individually.

General features of insurance programs are: they are based on historical data. they can be farm-based or area-based. indemnity is triggered if the revenue falls below some threshold. a producer needs to pay fee, premium, to participate in the program. the government may choose to subsidize the program.

## Insurance Market Failures

Two main issues that are associated with crop insurance (or any insurance for that matter) are *moral hazard* and *adverse selection*. Moral hazard implies that a farmer's optimal decision may be different with insurance as compared to that without insurance. Adverse selection implies that farmers that choose to insure at a given rate, are also the ones who are more exposed to risk.

### Moral Hazard

Moral hazard problems arise, when the insurer contracts on a risk-averse producer whose inputs are unobservable. With or without moral hazard, the contract is designed in such way that a farmer is willing to participate in the program. Under moral hazard, however, it is no longer optimal for the risk-neutral insurer (principal) to assume all risk; some residual risk must be borne by the risk-averse producer (agent).

The implications of the moral hazard problem are not as clear-cut as intuition might	suggest. On the one hand, being relieved of some of the consequences of low input use, the producer may reduce input intensity. On the other hand, if input use is risk-increasing, then a high-risk environment may cause the producer to use fewer inputs than a low-risk environment.

### Adverse Selection

When the insurer is not completely informed about the nature of the risk being insured, then the insurer faces the problem of adverse selection. Avoiding adverse selection may require the successful crop insurance program to identify, acquire, and skilfully use data that discriminate among different risks. While costly to implement, such data management procedures may be crucial	because, unless rates are perceived as being acceptable, the market may collapse.

Identifying a sufficiently large number of relatively homogeneous risks is a prerequisite for a successful contract. Another factor that can facilitate to sustain the contract is sufficiently high degree of risk--aversion among producers.


## Mitigating the Market Failures

While  moral hazard and adverse selection are conceptually distinct phenomena, they share information asymmetry as a common characteristic feature. To that end, these two issues can be interrelated, as illustrated in the following example: Consider a wheat and corn farmer who has one hectare of high quality land and one hectare of low quality land. Given the decision to insure wheat but not corn, the planting of wheat on poor quality land is moral hazard. Given the decision to plant wheat on poor quality land, the insuring wheat is adverse selection. 

Due to the informational nature of main barriers to successful crop insurance markets, the obvious solution is to facilitate better (ideally, complete) information. One approach to reduce adverse selection is to obtain and use farm-level (rather than area-level) information; but this creates incentives for moral hazard. Alternatively, area yield insurance can solve moral hazard and possibly mitigate adverse selection, but this will not completely alleviate the production risk.

Revenue insurance, instead of yield insurance, mitigates somewhat the incidence of moral hazard and adverse selection. It also serves the main purpose of crop insurance as it addresses the issue of income risk facing producers.

Yet another crop insurance mechanism, that can mitigate some of the aforementioned issues, is the so-called *weather derivatives*. Such insurance is applicable because weather is intrinsically linked with agricultural production. Weather derivatives are based on historical weather data of the area where farm is located. Indemnity is triggered if weather conditions are ``bad'' relative to the historical normal. But correlation (or the lack of it) with yields can be an issue (e.g., not al farms are located in close proximity to weather stations).
